### PR TITLE
Implement Swarm methods

### PR DESCRIPTION
**Pull request by axic**
There's a lot left for this to be complete, but it's a start. What do you think?

### CODE REVIEW

**Comment by axic** [comment]
This requires node.js >=5.7.0 as earlier versions had an off-by-one bug in `url.parse`, parsing

`bzz://f0934b1877f410e103d49256d02cf99227e8e62151b77e31cb82c7474696a8c1`

as

`host: f0934b1877f410e103d49256d02cf99227e8e62151b77e31cb82c7474696a8c`
`path: 1`

**Comment by axic** [comment]
@tcoulter I think merging this should be probably postponed until the Swarm RPC API is a bit more mature?

@zelig what do you think, how likely is it to change in the next few months?

**Comment by tcoulter** [comment]
@axic Alright. Let me know when you think we should merge. Otherwise looks good (though I didn't test it).

Speaking of tests, can you add some tests for it when you get a chance?

**Comment by axic** [comment]
I'll look into adding tests and trying to keep this aligned with any possible API changes in Swarm.

I hope it should be ready for merging after devcon2.

**Comment by tcoulter** [comment]
:+1: 👏

**Comment by axic** [comment]
Rebased against master, but still need to review it against the latest Swarm changes.

**Comment by axic** [comment]
Rebased and added support for real Swarm hashes. Still needs to be verified against geth 1.5.6.

**Comment by wackoisgod** [comment]
@axic Is there any plans to actually merge this at some point ?

**Comment by benjamincburns** [comment]
@axic - closing this one due to the way things have been moved around. If you think it'd apply cleanly without too much rework, perhaps reopen it against [trufflesuite/ganache-core](https://github.com/trufflesuite/ganache-core)?

**Pull request closed without merging**
