### PR TITLE
Add output for --help and -?

### PR DESCRIPTION
**Pull request by hoytech**
Not having help output has kind of annoyed me a few times. I cribbed most of it from the README but please feel free to fix it up of course if anything is wrong/misleading.

### CODE REVIEW

**Comment by benjamincburns** [comment]
Beautiful! This is something that has been bugging me, too.

**Comment by hoytech** [comment]
After I posted this PR, I noticed there are a few other similar ones pending also. Oh well. :)

**Comment by benjamincburns** [comment]
I'm new to the project, so it was a bit luck of the draw, I'm afraid. Yours is most recent, so it's likely also most up to date.

**Comment by hoytech** [comment]
Thanks!

**Pull request merged**
