### PR TITLE
Add docs for networkId option

### PR DESCRIPTION
**Pull request by LogvinovLeon**

### CODE REVIEW

**Comment by LogvinovLeon** [comment]
The test failure seems to be spurious or just a Travis Bug, cause the PR doesn't change anything except the docs. I'll reopen it to triger Travis to restart.

**Review by axic — APPROVED** [review]

**Comment by axic** [comment]
This seems to be duplicating #251. Can you discuss with @izqui the final wording?

**Comment by LogvinovLeon** [comment]
Didn't mention that one.

I described the option in both places and also mentioned, that it defaults to the id of the forked network, but this is such a small issue, that you could as well accept the first one. BTW, why didn't you do that 8 days ago in the first place?

**Comment by axic** [comment]
@LogvinovLeon I'm not the maintainer of this project, just helping @tcoulter with reviews

**Comment by tcoulter** [comment]
Added, and changed some wording. Thanks!

**Pull request merged**
