### PR TITLE
Move options to yargs

### PR DESCRIPTION
**Pull request by chevdor**
- Add help option and move options to yargs
  `testrpc --help
  `
- Fix for the generation of a given number of accounts
  `testrpc -t 3` would generated 10 accounts, this is fixed
- Version bump

### CODE REVIEW

**Comment by tcoulter** [comment]
Appreciate this pull request. There are a couple things that need to be discussed in general to make life easier for us.
- This PR adds multiple features at once, adding help documentation as well as fixing the `-t` option. The `-t` fix isn't controversial, but I'd like to make changes to the help documentation, which requires some discussion. It'd be easier to manage this if the fixes were separated into two different PRs (in this case, fix the `-t` feature first on its own, then add the `yargs` feature as a separate PR extending from that fix). Reviewing the changes with me beforehand could mitigate this issue as well (aside: I realize there's no single place to chat for the testrpc; the truffle or ethereumjs-lib gitter could work though). 
- If possible, don't bump the version when making a change. Often we'll merge multiple PRs at once and we want to be responsible for bumping the version when we're ready to release. Having it bumped in a PR makes it slightly more of a hassle in getting the PR merged, and can in some cases make the commit log unclear when reviewing it to see what a version bump includes.

In either case, I really appreciate your desire to contribute, and please keep submitting pull requests!

**Comment by chevdor** [comment]
Thanks for your feedback @tcoulter. Let me remove the version bump from this branch.
I will check if I can exclude the '-t' fix from here and make it a separate PR.

**Comment by chevdor** [comment]
@tcoulter here you go. Same PR without the version bump  and the -t fix (submitted as other PR).

**Comment by chevdor** [comment]
@tcoulter If I made any change to the -a/-t behavior, this is probably in this PR.
I based the options on the document but due to the contradiction for -a, I picked the following:

```
Usage: bin/testrpc [options...]

Options:
  --port, -p            The port to serve             [string] [default: "8545"]
  --hostname, -h        Hostname to listen on. Defaults to Node's
                        server.listen() default.                        [string]
  --debug               Output VM opcodes for debugging
                                                      [boolean] [default: false]
  --deterministic, -d   Generate deterministic addresses based on a pre-defined
                        mnemonic.                     [boolean] [default: false]
  --seed, -s            Use arbitrary data to generate the HD wallet mnemonic to
                        be used.       [string] [default: "TestRPC is awesome!"]
  --mnemonic, -m        Use a specific HD wallet mnemonic to generate initial
                        addresses.                                      [string]
  --total_accounts, -t  Number of accounts to generate at startup. [default: 10]
  --blocktime, -b       Specify blocktime in seconds for automatic mining.
                        Default is 0 and no auto-mining.            [default: 0]
  --gasPrice, -g        Use a custom Gas Price (defaults to 1)      [default: 1]
  --gasLimit, -l        Use a custom Gas Limit (defaults to 0x47E7C4)
                                                              [default: 4712388]
  --accounts, -a        Specify the accounts to generate at startup. testrpc
                        --account="<privatekey with 0x>,<balance in wei>"
                        [--account="<privatekey>,balance"]              [string]
  --fork, -f            Fork from another currently running Ethereum client at a
                        given block. Input should be the HTTP location and port
                        of the other client, e.g. http://localhost:8545. You can
                        optionally specify the block to fork from using an @
                        sign: http://localhost:8545@1599200
                                                      [boolean] [default: false]
  --network_id, -i      The network id                           [default: 1377]
  --verbose, -v         Tell me more!                 [boolean] [default: false]
  --help                Show some help                [boolean] [default: false]
  --version             Show the version              [boolean] [default: false]
```

I can adapt once we decide what is the best constellation of options. I think it is less error prone to have it the way I propose here than having confusion between -a being also --account and --accounts doing something else than -a while we anyway provide a single account to --accounts ....

So, as summary, I would suggest:
- -t for _T_otal accounts to create   (-n cannot be used, it is already used by --secure)
- --accounts Not in use, it creates confusion with --account
- -a or --account for a single account creation, --account can be used multiple times

**Comment by chevdor** [comment]
@tcoulter did you have a chance to have a look at those old PRs?

**Comment by derhuerst** [comment]
bump. (:

**Comment by chevdor** [comment]
Sounds like some conflicts to fix on my side since the main branch moved on. I will look at it once I find a little time. I would also love to have this PR merged.

**Comment by derhuerst** [comment]
another bump (:

**Comment by axic** [comment]
What is left for this to be merged?

**Comment by derhuerst** [comment]
@axic resolving merge conflicts

**Comment by chevdor** [comment]
I did not give up on that one :)
I am hoping to find some time today in the train on my way to EDCON to look into that again.

**Comment by chevdor** [comment]
Why wait so long? :)
@derhuerst my apologies for the wait and thanks for the multiple bumps. I am looking forward to getting this one merged as it will also allow merging the other smaller PRs that follow.

**Comment by chevdor** [comment]
OK, this PR should be ok to merge now.
I also resolved the conflicts related to the other PRs:  #166, #167 and #172.

image

**Comment by chevdor** [comment]
@tcoulter Any remaining issue preventing merging this PR?

**Comment by benjamincburns** [comment]
@chevdor I'm really sorry to see that this PR went for so long without a response. I've just joined the Truffle team, and I'll be maintaining this project for the foreseeable future. If I'm doing my job, PRs like this won't sit quite so long in the future.

Unfortunately with some of the other PRs I've recently merged it looks like we've gotten most of the way there with this change, so I'm inclined to close this. Thanks for your contribution nonetheless.

**Comment by chevdor** [comment]
@benjamincburns Happy to see things improving. Of course not so much to see my work trashed....
Can you point the "other PRs I've recently merged it looks like we've gotten most of the way there with this change"?

**Pull request closed without merging**
