### PR TITLE
eth_sign functionality

### PR DESCRIPTION
**Pull request by MrChico**
Now as described by yellow paper :)

### CODE REVIEW

**Comment by tcoulter** [comment]
Awesome @MrChico. Any chance you can write me a test or two for it (at least one) in `requests.js`?

**Comment by tcoulter** [comment]
Oh, and I'll be upgrading `ethereumjs-util` to `^4.0.1` soon. Could you change your `package.json` to `^4.0.1` and ensure it still works?

**Comment by MrChico** [comment]
Sure. Will do

**Comment by MrChico** [comment]
tests added

**Comment by MrChico** [comment]
But doesn't pass tests yet. Don't pull just yet :)

**Comment by MrChico** [comment]
Now passing

**Comment by tcoulter** [comment]
Merged to master. Thanks @MrChico!

**Review by dustpan28645 — COMMENTED** [review]
Good work

**Pull request merged**
