### PR TITLE
Sets default gas price to 0.02 szabo

### PR DESCRIPTION
**Pull request by uzyn**
to better mimic current livenet and testnet's gas price.

I understand that gas price is changeable via option, however I feel that a much larger default than the current 1 would probably be better even during development.

### CODE REVIEW

**Review by chevdor — COMMENTED** [review]
I would disagree with this changes for the following reason: changing that now means we need to keep up with the changes in price when it goes up or down.

Moreover, each user can use the --gasPrice (-g) option to provide the right value at a given time.

**Comment by uzyn** [comment]
A more reasonable default is still better than 1 wei, which is multiple orders of magnitude smaller than livenet's value.

Regarding keeping up with changes, I am fine with either of the follow 2 approaches:
1. Keep up with live net's hardcoded value, or
2. Do not keep up, but have the default at a a more sensible value than 1 wei.

Noticed the PR is now having conflicts. Let me know if I should resubmit.

**Comment by tcoulter** [comment]
It's a simple PR; not sure why there's conflicts. No need to resubmit. We'll take care of it if it's accepted.

@area and I have been talking about fixing #130 in the next big release (3.0). This feature is similar. @area - can I get your view on it?

**Comment by area** [comment]
Yeah, I can't see any reason why this isn't a net benefit. Even if the price changes on the live net, we can certainly be a lot more correct than ten orders of magnitude wrong.

A knock-on effect that might want to be considered is increasing the default balance accounts start with, given accounts will be spending a lot more on gas now, but I could equally see that being left alone - 100 Ether is very reasonable.

**Comment by tcoulter** [comment]
There was a conflict because `gasPriceVal` was moved to the state manager. 

I've merged this into the `develop` branch. Will close this ticket to show 3.0 milestone progress.

Regarding the default gas price, there's a discussion in #109. I'm on the fence about raising it or leaving it where it is. If 100 ETH is plenty, we should probably stick with that for now. However, if there are reports that people are running out of funds during unit tests than I'd definitely consider raising it.

**Pull request closed without merging**
