### PR TITLE
Make web3.eth.sign compatible with new eth_sign API

### PR DESCRIPTION
**Pull request by yusefnapora**
As discussed in #243, the eth_sign api now accepts an arbitrary message, which is prefixed with a fixed header + the length of the message, then run through keccak256 before signing.

This updates the `sign` method in `lib/statemanager.js` to produce the new signatures, and updates the tests in `test/requests.js` - I managed to find another message that produces a signature with a zero-prefixed `r` component, so hopefully that test is still valid.

Actually recovering the public key / address for a signature is quite a bit more involved now, but that's due to the API change.  Price of progress, I guess.

Let me know if anything needs tweaking.

### CODE REVIEW

**Comment by axic** [comment]
I think it would be great adding this functionality to the underlying library, `ethereumjs-util`. Would you be interested looking into that?

**Comment by yusefnapora** [comment]
I opened the PR in ethereumjs-util - I'm happy to update this one to use it once it gets merged.

**Comment by yusefnapora** [comment]
Now that there's a new version of ethereumjs-util with the `hashPersonalMessage` helper, I updated this PR to use it.  

I had to make a couple small changes to get the tests passing again with ethereumjs-util 5.x - the API for `ecrecover` changed, and I guess maybe `bufferToInt` got more strict, because it was throwing during `txhelper.fromJSON` complaining that the input was > 53 bits.

Let me know if this needs anything else :)

**Review by parkan — APPROVED** [review]
This API divergence is breaking our build, any chance this can get merged?

**Comment by tcoulter** [comment]
Apologies for the delay. Thanks a lot @yusefnapora!

**Comment by yusefnapora** [comment]
Sweet, glad to help 😄

**Pull request merged**
