### PR TITLE
Add documentation on docker image use

### PR DESCRIPTION
**Pull request by ghost**
... So people with little or zero docker experience could use it.

Also, I've checked that `https://hub.docker.com/r/ethereumjs/` returns 404. Are you interested on having your docker hub account?

Anyways, I've built an image myself based on 21f2a7a, in [my docker hub account](https://hub.docker.com/r/hermanjunge/eth-testrpc/tags/)

### CODE REVIEW

**Comment by tcoulter** [comment]
This is effectively a dupe of #62. Will eventually get to this. I'll talk to ethereumjs people about securing the name.

**Comment by axic** [comment]
Can this or #62 be merged?

**Comment by MicahZoltu** [comment]
One can create Docker Hub organizations.  It feels like `ethereumjs` should be an organization, not a user.  If you all want, I can create an organization and add whomever to it and/or give ownership to whomever if that helps move things forward.

**Comment by tcoulter** [comment]
I merged another branch that had docker instructions a few minutes ago. Can one of you check to see if these instructions are correct, vs. the instructions in this PR? https://github.com/ethereumjs/testrpc#docker

I'm not a docker user so would love your help. If the instructions are incorrect and I should favor these instructions, let me know. Also, I'm very happy if someone would like to create and manage the ethereumjs docker org.

**Comment by MicahZoltu** [comment]
@tcoulter The instructions in this PR are a bit more verbose/thorough, but both these and the current set are correct.  Offer still stands to create a Docker organization for `ethereumjs` and setting up automated builds so we can get some images uploaded.

**Comment by tcoulter** [comment]
I'm open to you setting that up. I'm sure others would be as well.

**Comment by ghost** [comment]
I was checking my open PRs. I guess there will be _no further action_ to this one. We close it?

**Pull request closed without merging**
