### PR TITLE
Adding failing test reproducing issue #122

### PR DESCRIPTION
**Pull request by graup**
See #122

### CODE REVIEW

**Comment by tcoulter** [comment]
:+1: Good test. Thanks!

**Comment by derhuerst** [comment]
bump. (:

**Comment by tcoulter** [comment]
I updated the test for the latest version of solidity. It's on the graup-bug-double-spent-ether branch. 

This bug has been fixed for quite some time (see #122) but is waiting on changes upstream. We may have to consider running on a custom fork, which I'm not happy about.

**Comment by benjamincburns** [comment]
Since this issue was actually rooted in [ethereumjs/ethereumjs-vm](https://github.com/ethereumjs/ethereumjs-vm), we're going to trust their testing is adequate to guard against this issue regressing.

**Pull request closed without merging**
