### PR TITLE
fix: added version option

### PR DESCRIPTION
**Pull request by roppa**
Issue #526. Added yargs version option

### CODE REVIEW

**Comment by mikeseese** [comment]
Hi @roppa, thanks for contributing! Did you test this yet? I'm get `unknown` when I execute the below command:
```
build/cli.node.js --version
```

**Comment by roppa** [comment]
Ah I see. I tried from the actual file `node cli.js --version`. I *think* yargs is looking for the package.json file in the same location as the cli file is being executed

**Comment by mikeseese** [comment]
Ya I think webpack somehow is messing up yargs from retrieving the version of the package.json file. I committed https://github.com/trufflesuite/ganache-cli/pull/534/commits/0266322336e095a0c7f144203acbf57793b6868a (which was super cool. didn't know I could commit to PRs like that) which simply passes the package.json version down to the `args.js` module.

**Review by mikeseese — APPROVED** [review]
Looks good! Thanks @roppa for submitting this! Will wait for CI to finish before merging

**Comment by roppa** [comment]
Awesome! Thanks!

**Pull request merged**
