### PR TITLE
Addition of eth_getBlockTransactionCountByNumber and eth_getBlockTransactionCountByHash

### PR DESCRIPTION
**Pull request by conroydamien**
Added `eth_getBlockTransactionCountByNumber` and `eth_getBlockTransactionCountByHash`.
Updated `README.md` to reflect change.

### CODE REVIEW

**Comment by conroydamien** [comment]
I had an issue using https://github.com/etherparty/explorer with TestRPC. Explorer seems to rely on web3.eth.getBlockTransactionCount. Thanks for TestRPC!

**Review by tcoulter — COMMENTED** [review]
Thanks! Good addition. Would you mind writing a test within `test/requests.js` to test these methods?

**Comment by conroydamien** [comment]
Hi! I've added a couple of tests... The test for `eth_getBlockTransactionCountByNumber` uses `accounts[2]` to pay for a transaction, I found that using `accounts[0]` was causing later tests that relied on `accounts[0]` to fail... I hope that's OK... Thanks!

**Comment by tcoulter** [comment]
That's perfect. Apologies for the late response. Thanks for the submission!

**Comment by conroydamien** [comment]
Thanks! Delighted to be able to give a little to the project!

**Pull request merged**
